export const GET_PHONE_BOOK_DATA = 'GET_PHONE_BOOK_DATA';
export const LOAD_MODEMS = 'LOAD_MODEMS';
export const CONNECTING_MODEM = 'CONNECTING_MODEM'
export const INITIALIZING_MODEM = 'INITIALIZING_MODEM'
export const CHANGE_MODEM_STATUS = 'CHANGE_MODEM_STATUS'
